export const Product4 =[
    {
        id: 20,
        name: 'Street Cap',
        brand: 'NY',
        price: '₹ 1,995.00',
        image: '/Images/Acc/1.jpeg',
        colors: 'Black/Biege',
      },
      {
        id: 21,
        name: 'Sunglass',
        brand: 'URBAN MONKEY',
        price: '₹ 3,995.00',
        image: '/Images/Acc/2.jpeg',
        colors: 'Black',
      },
      {
        id: 22,
        name: 'Chain',
        brand: 'Street Vogue',
        price: '₹ 995.00',
        image: '/Images/Acc/3.jpeg',
        colors: 'Silver/Golden',
      },
      {
        id: 23,
        name: 'Hat',
        brand: 'Street Vogue',
        price: '₹ 2,495.00',
        image: '/Images/Acc/4.jpeg',
        colors: 'Black',
      },
      {
        id: 24,
        name: 'Sunglass',
        brand: 'Street Vogue',
        price: '₹ 3,995.00',
        image: '/Images/Acc/5.jpeg',
        colors: 'Black',
      },
      {
        id: 25,
        name: 'Street Cap',
        brand: 'SW',
        price: '₹ 1,995.00',
        image: '/Images/Acc/8.jpeg',
        colors: 'Brown/Navy Blue/Red/Black',
      },
      {
        id: 26,
        name: 'Sunglass',
        brand: 'SW',
        price: '₹ 1,495.00',
        image: '/Images/Acc/6.jpeg',
        colors: 'Black/Biege',
      },
]